version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/do_it_django/
    - source: ./nginx
      destination: /home/ubuntu/do_it_django/nginx
    - source: ./docker-compose.yaml
      destination: /home/ubuntu/do_it_django
    - source: ./.env
      destination: /home/ubuntu/do_it_django
    - source: ./config/
      destination: /home/ubuntu/do_it_django/config
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/ubuntu/do_it_django
      pattern: '**'
      owner: root
      group: root

hooks:
    AfterInstall:
        - location: scripts/after_deploy.sh
          timeout: 2000
          runas: root
