version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/do_it_django/do_it_django_back
    - source: /do_it_django/nginx
      destination: /home/ubuntu/do_it_django/nginx
    - source: /docker-compose.yml
      destination: /home/ubuntu/do_it_django
    - source: /.env
      destination: /home/ubuntu/do_it_django
    - source: /config/
      destination: /home/ubuntu/do_it_django/config
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/ubuntu/do_it_django
      pattern: '**'
      owner: root
      group: root

hooks:
    AfterInstall:
        - location: scripts/after-deploy.sh
          timeout: 2000
          runas: root
